name: Test

on:
  push:
    branches-ignore:
      - release

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Unit tests
        run: make test.unit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
